Repository fedora-sysv/initscripts, pull requests merged in 2018-02, with the labels that each got.

#164 [RHEL7] init.d/functions: fix sourcing for ksh
  rc.d/init.d/functions
Labels: RHEL7, bugfix

#165 [RHEL6] init.d/functions: fix sourcing for ksh
  rc.d/init.d/functions
Labels: RHEL6, bugfix

#166 [RHEL6] 9.03.59 release
  initscripts.spec
Labels: RHEL6, release

#168 spec: add gcc to BuildRequires
  initscripts.spec
Labels: Fedora.next
