Repository fedora-sysv/initscripts, pull requests merged in 2018-05, with the labels that each got.

#191 po/xgettext_sh*: converted to use to python3
  po/xgettext_sh
  po/xgettext_sh.py
Labels: Fedora.next, enhancement

#192 po/xgettext_sh.py: fix for indentation of previous commit
  po/xgettext_sh.py
Labels: Fedora.next, bugfix

#194 netconsole: LSB header added
  rc.d/init.d/netconsole
Labels: Fedora.next, enhancement

#193 ifdown-eth: no longer needed 'pidof -x dhclient' condition removed
  sysconfig/network-scripts/ifdown-eth
Labels: Fedora.next, bugfix

#183 network-functions: add error messages for bonding installation
  sysconfig/network-scripts/network-functions
Labels: Fedora.next, enhancement

#176 network-functions: use tr to upper case strings rather than awk
  sysconfig/network-scripts/network-functions
Labels: Fedora.next, enhancement

#170 specfile: remove the systemctl call in the %postun phase
  initscripts.spec
Labels: Fedora.next, bugfix

#174 use proper shebang
  service
  sys-unconfig
  sysconfig/network-scripts/ifdown-sit
  sysconfig/network-scripts/ifup-ipv6
  sysconfig/network-scripts/init.ipv6-global
Labels: Fedora.next, enhancement

#177 RHEL-7 | network.service: 'reload' removed
  rc.d/init.d/network
Labels: BZ missing ACKs, RHEL7, bugfix

#182 RHEL-7 | sysctl.conf.s390: drop SHMALL and SHMMAX
  sysctl.conf.s390
Labels: BZ missing ACKs, RHEL7, enhancement

#184 RHEL-7 | network-functions: add error messages for bonding installation
  sysconfig/network-scripts/network-functions
Labels: RHEL7, enhancement

#189 sysconfig/readonly-root: Clarify the usage of readonly-root.
  sysconfig/readonly-root
Labels: Fedora.next, enhancement

#190 RHEL-7 | sysconfig/readonly-root: Clarify the usage of readonly-root.
  sysconfig/readonly-root
Labels: RHEL7, enhancement

#199 [Fedora] 9.80 release
  initscripts.spec
Labels: Fedora.next, release

#195 RHEL-7 | rhel-autorelabel: set UEFI BootNext == BootCurrent
  systemd/rhel-autorelabel
Labels: RHEL7, bugfix

#200 RHEL-7 | 9.49.42
  initscripts.spec
Labels: RHEL7, release

#201 fedora-readonly: command substitution warning fixed (null-byte input)
  systemd/fedora-readonly
Labels: Fedora.next, bugfix
