Repository fedora-sysv/initscripts, pull requests merged in 2019-10, with the labels that each got.

#288 rc.local: Initscripts no longer care about rc.local
  Makefile
  initscripts.spec
Labels: Fedora.next, bug-clone

#62 network-function: bridges are created by ifup-eth
  network-scripts/network-functions
Labels: Fedora.next, bug-clone

#289 rc.local: Initscripts no longer care about rc.local
  Makefile
  initscripts.spec
Labels: RHEL8, bugfix, merge ready

#281 ifup-eth: Check that device name is set
  network-scripts/ifup-eth
Labels: RHEL8, bug-clone, merge ready

#267 Add ip6gre tunnel option - rhel8
  doc/sysconfig.txt
  network-scripts/ifup-tunnel
  network-scripts/network-functions
Labels: RHEL8, bug-clone, merge ready

#275 network: don't fail with IFDOWN_ON_SHUTDOWN
  etc/rc.d/init.d/network
Labels: RHEL8, bugfix, merge ready

#290 network-function: bridges are created by ifup-eth
  network-scripts/network-functions
Labels: RHEL8, bug-clone, merge ready
