Repository fedora-sysv/initscripts, pull requests merged in 2019-08, with the labels that each got.

#262 Configure autorelabel service to output to journal and to console if set
  systemd/system/rhel-autorelabel.service
Labels: RHEL7, bugfix

#269 network: don't fail with IFDOWN_ON_SHUTDOWN - RHEL7
  rc.d/init.d/network
Labels: RHEL7, bugfix

#272 rc.d/functions: fix escape sequence being output under systemd servic…
  etc/rc.d/init.d/functions
Labels: Fedora.next, bugfix

#274 10.00.3
  initscripts.spec
Labels: RHEL8, release

#276 Fix missing python3 during build phase
  Makefile
  initscripts.spec
  po/Makefile
Labels: Fedora.next, enhancement, merge ready

#279 ifup-eth: Check that device name is set
  network-scripts/ifup-eth
Labels: Fedora.next, bugfix

#264 Add ip6gre tunnel option - rhel7
  sysconfig.txt
  sysconfig/network-scripts/ifup-tunnel
  sysconfig/network-scripts/network-functions
Labels: RHEL7, bugfix, merge ready, new feature

#280 ifup-eth: Check that device name is set
  sysconfig/network-scripts/ifup-eth
Labels: RHEL7, bugfix, merge ready

#282 9.49.49
  initscripts.spec
Labels: RHEL7, release

#278 Fix bug in service(8)
  man/service.8
Labels: Fedora.next, enhancement, merge ready

#283 ifup-eth: Fix bridge setting stp option
  network-scripts/ifup-eth
Labels: Fedora.next, bugfix, merge ready

#284 [RHEL8] ifup-eth: Fix bridge setting stp option
  network-scripts/ifup-eth
Labels: RHEL8, bugfix, merge ready
