Repository fedora-sysv/initscripts, pull requests merged in 2020-07, with the labels that each got.

#321 Fix spelling of SELinux
  initscripts.spec
Labels: Fedora.next, enhancement, merge ready

#322 Fix spelling, for more info
  network-scripts/network-functions-ipv6
Labels: Fedora.next, enhancement, merge ready

#323 Correct spelling, IP, …
  network-scripts/ifup-aliases
Labels: Fedora.next, enhancement, merge ready

#326 rwtab: Add support for chrony
  etc/rwtab
Labels: Fedora.next, bugfix, merge ready

#332 Maintain permisision to set umask
  network-scripts/network-functions
Labels: Fedora.next, enhancement, merge ready

#334 Add optional 'dev' keyword
  network-scripts/ifup
  network-scripts/ifup-eth
Labels: Fedora.next, bugfix, merge ready

#335 Add optional 'dev' keyword
  network-scripts/ifup
  network-scripts/ifup-eth
Labels: RHEL8, bugfix, merge ready

#333 Fix spacing in Makefile
  Makefile
Labels: Fedora.next, enhancement, merge ready
