Repository fedora-sysv/initscripts, pull requests merged in 2021-11, with the labels that each got.

#398 ci: disable comments under opened PR in order to fix CI
  .github/workflows/shellcheck_test.yml
Labels: enhancement, CI

#399 Add LGTM badges to README
  README.md
Labels: enhancement

#400 Translations update from Fedora Weblate
  po/de.po
Labels: documentation
