Repository fedora-sysv/initscripts, pull requests merged in 2021-05, with the labels that each got.

#373 spec: Move service script into subpackage
  etc/rc.d/init.d/functions
  initscripts.spec
  usr/sbin/service
Labels: Fedora.next, enhancement, merge ready

#371 Translations update from Weblate
  po/es.po
  po/fi.po
  po/ko.po
  po/si.po
Labels: Fedora.next, documentation, merge ready

#374 spec: Initscripts now requires chkconfig
  initscripts.spec
Labels: CI-reviewed, Fedora.next, enhancement
