Repository fedora-sysv/initscripts, pull requests merged in 2021-01, with the labels that each got.

#359 remove rename_device_lock when process does not exist
  src/rename_device.c
Labels: Fedora.next, bugfix, merge ready

#362 doc: Documents ifcfg option LINKSTATUS
  doc/sysconfig.txt
Labels: Fedora.next, documentation, merge ready

#364 doc: Documents RES_OPTIONS option
  doc/sysconfig.txt
Labels: Fedora.next, documentation, merge ready

#363 doc: Documents ifcfg option LINKSTATUS
  doc/sysconfig.txt
Labels: RHEL8, documentation, merge ready

#366 spec: sync with Fedora
  initscripts.spec
Labels: Fedora.next, enhancement, merge ready
