Repository fedora-sysv/initscripts, pull requests merged in 2022-02, with the labels that each got.

#417 Translations update from Fedora Weblate
  po/fi.po
Labels: Fedora, documentation

#418 ci: Use Differential ShellCheck action
  .github/.diff-shellcheck-exceptions.txt
  .github/.diff.shellcheck-scripts.txt
  .github/workflows/check-shell.sh
  .github/workflows/functions.sh
  .github/workflows/shellcheck_test.yml
  README.md
Labels: RHEL8, CI, documentation

#419 ci: Use Differential ShellCheck action
  .github/.diff-shellcheck-exceptions.txt
  .github/.diff.shellcheck-scripts.txt
  .github/workflows/shellcheck_test.yml
  README.md
Labels: CI, RHEL9, documentation

#420 ci: Update `.packit.yml` to run on `c8s` `c9s` and `rawhide`
  .packit.yml
Labels: Fedora, CI

#422 packit: Run copr builds on release as well
  .packit.yml
Labels: Fedora, CI

#423 ci: Update `.packit.yml` to run on `c8s`
  .packit.yml
Labels: RHEL8, CI

#424 ci: Update `.packit.yml` to run on `c9s`
  .packit.yml
Labels: CI, RHEL9

#425 spec: network-scripts needs to depend on dbus-tools for NetworkManager detection
  initscripts.spec
Labels: bugfix, Fedora

#426 spec: Move `rename_device` to subpackage `initscripts-rename-device`
  initscripts.spec
Labels: enhancement, Fedora

#427 spec: Drop unnecessary obsoletes
  initscripts.spec
Labels: bugfix, Fedora

#428 (#2057917) spec: Move rename_device to subpackage initscripts-rename-device
  initscripts.spec
Labels: bugfix, RHEL9

#429 (#2057917) spec: Update initscripts Obsoletes
  initscripts.spec
Labels: bugfix, RHEL9
