Repository fedora-sysv/initscripts, pull requests merged in 2024-08, with the labels that each got.

#483 Translations update from Fedora Weblate
  po/tr.po
Labels: Fedora, documentation

#485 Netconsole random fixes
  usr/libexec/netconsole
Labels: Fedora

#484 Translations update from Fedora Weblate
  po/tr.po
Labels: Fedora, documentation

#486 netconsole fixes
  usr/libexec/netconsole
Labels: RHEL9
