Repository fedora-sysv/initscripts, pull requests merged in 2024-03, with the labels that each got.

#477 Memory leak
  src/rename_device.c
Labels: bugfix, Fedora

#476 Translations update from Fedora Weblate
  po/ka.po
Labels: Fedora, documentation

#478 (RHEL-28191) rename_device: free path after it is used
  src/rename_device.c
Labels: RHEL9

#479 Sync spec with c9s
  initscripts.spec
Labels: RHEL9
