Repository fedora-sysv/initscripts, pull requests merged in 2024-02, with the labels that each got.

#473 fedora: don't build network-scripts rpm in f40+
  Makefile
  initscripts.spec
Labels: Fedora, RHEL10

#475 ifup-routes: print warning when ADDRESS0 entry is missing
  network-scripts/ifup-routes
Labels: Fedora, network-scripts

#472 (RHEL-23313) Fix parsing of statetab files when it contains space characters
  usr/libexec/readonly-root
Labels: RHEL9
